name: Go Tests

on: ["push"]

permissions:
  checks: write
  pull-requests: write
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: arn:aws:iam::407461997746:role/github-actions-Role-56IHHM969DKJ
            aws-region: eu-west-2
      # look up /s3-access-point/s3-check-role-2025/alias from ssm parameter store, fail if not found
      - name: Look up S3 Access Point Alias
        id: ssm
        run: |
          AP_ALIAS=$(aws ssm get-parameter --name "/s3-access-point/s3-check-role-2025/alias" --query "Parameter.Value" --output text)
          echo "S3 Access Point Alias: $AP_ALIAS"
          echo "AP_ALIAS=${AP_ALIAS}" >> $GITHUB_ENV
      - uses: actions/setup-go@v5
      - name: test
        working-directory: go
        run: go test ./...