name: Terraform and Tests

on: ["push"]

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    outputs:
      alias: ${{ steps.get_alias.outputs.ALIAS }}
    steps:
      - uses: actions/checkout@v5
      - uses: aws-actions/configure-aws-credentials@v5
        with:
            role-to-assume: arn:aws:iam::407461997746:role/github-actions-Role-56IHHM969DKJ
            aws-region: eu-west-2
            allowed-actors: '*'
      - uses: hashicorp/setup-terraform@v3
      - run: make
      - id: get_alias
        run: |
          ALIAS=$(aws s3control get-access-point --name s3-check-role-2025-ap --account-id 407461997746 | jq -r .Alias)
          echo "ALIAS=$ALIAS" >> $GITHUB_OUTPUT

  go-test:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - uses: actions/checkout@v5
      - uses: aws-actions/configure-aws-credentials@v5
        with:
            role-to-assume: arn:aws:iam::407461997746:role/github-actions-Role-56IHHM969DKJ
            aws-region: eu-west-2
            allowed-actors: '*'
      - uses: actions/setup-go@v6
      - name: test
        working-directory: go
        run: go test ./...
        env:
          AP_ALIAS: ${{ needs.terraform.outputs.alias }}
