on: ["push"]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: arn:aws:iam::407461997746:role/github-actions-Role-56IHHM969DKJ
            aws-region: eu-west-2
      - uses: astral-sh/setup-uv@v6
      - name: Run tests
        working-directory: tests
        run: make

      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: always()  # Ensure report is published even if tests fail
        with:
          name: Pytest Results
          path: tests/report.xml
          reporter: pytest-junit